FROM --platform=arm64 apache/airflow:2.7.3

# Install system dependencies
USER root
RUN apt-get update && apt-get install -y \
    pkg-config \
    libhdf5-dev \
    python3-dev \
    build-essential \
    gcc \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch to the airflow user
USER airflow

# Upgrade pip
RUN pip install --upgrade pip

COPY requirements-airflow.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements-airflow.txt
